# Site settings
title: Yearly Decisions
description: To live is to make decisions, choices. Data enables us to do this better.
cover: assets/images/fields.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/daily-decisions/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://moniquewong.github.io" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: moniquewong #github username
repo: daily-decisions #github repository
branch: master #branch
relative_source: ../daily-decisions/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://moniquewong.github.io/daily-decisions/
source_url:  https://moniquewong.github.io/daily-decisions/ #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
